version: '3.8'

services:
  company:
    build:
      context: .
      dockerfile: ./company/Dockerfile
    container_name: company-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  gym:
    build:
      context: .
      dockerfile: ./gym/Dockerfile
    container_name: gym-app
    restart: always
    working_dir: /var/www/
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1